steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_REGION=europe-west3'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-hello-world-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'service.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_REGION=europe-west3'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-hello-world-cluster'

options:
  logging: CLOUD_LOGGING_ONLY  
