# Automatically redirect HTTP calls to HTTPS
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: gke-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
